### ISSUE TITLE
El mapa no carga en Firefox (v52.0 Linux 64-bit)

### ISSUE THREAD

**Issue by martjanz** [datosgobar/densidad-poblacion#1]
Al cargar https://datosgobar.github.io/densidad-poblacion/ se muestran las barras superiores y el cuadro de referencia (abajo a la izquierda) pero el mapa queda en con el spinner girando y el texto _Cargando el mapa..._

Comparándolo con Chrome, donde sí se muestra bien, encuentro que en Firefox hay dos requests que están devolviendo 404 y en Chrome ni siquiera está pidiendo:

- `GET https://datosgobar.github.io/densidad-poblacion/public/style/css/bootstrap.min.css.map`
- `GET https://datosgobar.github.io/densidad-poblacion/public/style/css/poncho.css.map`

**Comment by framlopez** [comment]
Hola, @martjanz

Gracias por escribirnos. Ya solucionamos el problema.

Efectivamente había un error: la aplicación esperaba respuesta del usuario para definir la ubicación en el mapa. Si no la tenía, la carga no sucedía.

Muchas gracias otra vez. Esperamos que puedas navegar sin problemas ahora.
